sudo: required
services: docker
language: python
python: '3.6'
before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
env:
  global:
  - IMAGE_NAME=nielsbohr/ssh-mount-dummy
  - IMAGE_VERS=latest
  - secure: erbjVEp3GDzhghzsChYsy4uCLyjb3Ah8BA18wtuu0JlSma7xgjw24KUF7br8NsEPVUdO84Q5cJeioEsn04UG1Bch/OfjjZppOnFdRszzA+Dln7pPjozma2hTaBKJLhYcGKjKraUoLAqSJT2RQrJZqZTmF1+qGAFfZweUfqI3LOSCoGM6sfoESoCEhk+E1ZHdva74bWlwobRe3p9fZTBm2lJxwmbA+12a5IXaMIHsrHrcj+LlVSmp4Eci84VuDdD1T2vtdYX2nQwElbX9kgN0Ms5QPPVFy5Cch7ofjMf4xBAJwcHmmYz/NueesGWAikPbHYHDodNxfG8ADhEK4ZibuLlmJlsBvWdsWiOCZjSKQQMFUYp0imJIxZDutfrD4h4UGhWvjdtS+e4ZPeyrqCFgwZ37r/BirFXEpHKAzg0mtKH3C8quqhbcnP8eU9+394ZvM30FX5S7tHmTii3t4fP3Tv1GRWx6Fuw5y7UU7QDwLR8ZFpRAztMr0TRQ7KHG3yl6lthVfX5sxxjHMfVXpFx5L6dnhIHfdsnoWdTN4fXPmsBxEMxSHkHkqFRjcDN5WvQ9Lt/mmQMONc/n+URGl+gO5hivsuhd39CgoK6CuyAnVxIF7cJGBPs9evMX1beb4zK3zEpUFOjOj6YXz2iFMyCnPAWgd2V0yVdiOlPB6HDItbQ=
  - secure: cyMzacTOGjNxQl7wbyaDkjxGPNgjx2DYmL2/UjJLrdEfWhykbd5GAyj09lGRUOAX1ZOnVmOGx4MS26GANx88paxfOi8flUPWgkVilqWbs2dDRnud2DgBTIbzAkikF/VDXKXP0vUYVtQQ1Lu2L/OFxZFrPPgy8FZeOnM3QLTFKuMipFTrd7c9QTt1lQ/4LcHX8iII+/gqXxUvBuOQYJ6h+U/oTiBXS8AB6A/LYu/iOFebaWY5NPIvlLG8ZbADjOqG6bhGiEGIyzvYXDGfsBXqOkW1ZdnxKB8pvUXWGjk7DSkxtHj4CDFRt7cgfio3vhWi0pWFK1+KwNiSPOs5dR1ldACSq0njaIjG8a7Jqrxk5ljgtl2DrEKpiFhvUKKVSaBAxOvebByKlo1jr95MYhUVTLN4RV2SXphqQzEhcJi3iJvu0hE7eZmJMns4rpJuZ1I//5JSARVD6pT/Qg9ZjEvMjuM1PRrKjuNJZ81vrR/BbOQ+Jt0cuRaxhnUKeNEuGywF0uOgucQ+Hg1LXClaZeqJLIN4Bt7GrUSNylJivVi/pSR3q7waqy6t2aNwgToah2vDZPAuhsKHIiJO4s6AwmkWYHvTk0v7Dz/TqA+OJUoX7Lxzn+27KzTdzbLmkvZpBuoCWCr8KT9MMc5pLWUkUSXbY4QyLen4nHubqPLh48j2LwY=
install:
- pip install -r tests/requirements.txt
script:
- flake8
- pytest -s -v tests/
before_deploy:
- docker build -t "${IMAGE_NAME}":latest .
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
notifications:
  slack: raz-s:se1PurXsQJv03nBZa9XWMOOS
